import Head from "next/head";
import { Inter } from "next/font/google";
import Link from "next/link";
import Svg from "@/components/Svg";
import Layout from "@/components/layout";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Anaele Nnaemeka</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* Header Section */}
        <Header />

        {/* About Me section */}

        <div class="block pt-9 md:flex">
          <div class="pb-6  md:p-0 w-2/12">
            <h2 class="font-xs font-light tracking-widest text-sm text-gray-600 leading-normal uppercase text-right pr-20">
              About Me
            </h2>
          </div>
          <div class=" text-lg text-gray-600 font-light w-8/12 ">
            <div class="mb-6">
              <p className="text-justify">
                Hi, I am a Software Engineer with extensive years of experience
                in developing and building interactive web applications using
                software Technologies such as HTML, CSS, JavaScript, React,
                Redux, Nextjs, NodeJs, ExpressJs, CMS and MongoDB. I decompose
                complex problems into logic and scalable UI components using
                JavaScript and TypeScript frameworks to build cutting edge Web
                Applications.
              </p>
            </div>
          </div>
        </div>

        {/* Skills */}
        <div class="block pt-9 md:flex">
          <div class="pb-6  w-2/12 md:p-0">
            <h2 class="font-xs font-light tracking-widest text-sm text-gray-600 leading-normal uppercase text-right pr-20">
              Skills
            </h2>
          </div>
          <div class="text-lg text-gray-600 font-light  w-8/12 ">
            <div class="mb-6">
              <h3 class="font-semibold text-gray-900 pb-1 ">Languages</h3>
              <p class="text-md text-gray-600 font-light">
                JavaScript (ES6+), TypeScript, HTML5, CSS 3, SASS, Node.js,
                Express.js, React, NextJs, GraphQL.
              </p>
            </div>
            <div class="mb-6">
              <h3 class="font-semibold text-gray-900 pb-1 ">
                Frameworks &amp; Tools
              </h3>
              <p class="text-md text-gray-600 font-light">
                ReactJs, NextJs, Gatsby Tailwind CSS, Material-UI, Bootstrap
                CSS, Vite, Chakra-UI, ExpressJs, Redux, NPM, Webpack, Firebase,
                Strapi, Git & GitHub, Netlify, Vercel, Story book.
              </p>
            </div>
            <div class="mb-6">
              <h3 class="font-semibold text-gray-900 pb-1 ">Databases</h3>
              <p class="text-md text-gray-600 font-light">
                MongoDB, PostreSQL, MySQL
              </p>
            </div>
            <div class="mb-6">
              <h3 class="font-semibold text-gray-900 pb-1 ">Other</h3>
              <p class="text-md text-gray-600 font-light">
                Docker, Amazon Web Services (AWS), CI / CD, Microservices, API
                design, Agile / Scrum
              </p>
            </div>
          </div>
        </div>

        {/* The Blog */}
        <div class="block pt-9 md:flex">
          <div class="pb-6  w-2/12 md:p-0">
            <h2 class="font-xs font-light tracking-widest text-sm text-gray-600 leading-normal uppercase text-right pr-20">
              Experience
            </h2>
          </div>
          <div class="text-lg text-gray-600 font-light w-8/12">
            <div class="mb-6">
              <h3 class="font-semibold text-gray-900 pb-1  hover:text-black">
                <a href="https://www.nexthandle.com/">Tinq Lab</a>
              </h3>
              <p class="text-md text-gray-600 font-light">
                Frontend Engineer{" "}
                <span className="pl-12 text-sm italic">March - Present</span>
              </p>
              <hr className="mt-4" />
            </div>

            <div class="mb-6">
              <h3 class="font-semibold text-gray-900 pb-1  hover:text-black">
                <a href="https://www.nexthandle.com/">Nexthandle</a>
              </h3>
              <p class="text-md text-gray-600 font-light">
                Frontend Engineer{" "}
                <span className="pl-12 text-sm italic">
                  April 2022 - March 2023
                </span>
              </p>
              <hr className="mt-4" />
            </div>

            {/* Xerde */}
            <div class="mb-6">
              <h3 class="font-semibold text-gray-900 pb-1  hover:text-black">
                <a href="https://www.xerdetech.com/">Xerde</a>
              </h3>
              <p class="text-md text-gray-600 font-light">
                Software Engineer | Facilitator{" "}
                <span className="pl-12 text-sm italic">
                  June 2022 - March 2023
                </span>
              </p>
              <hr className="mt-4" />
            </div>

            {/* Hasob */}
            <div class="mb-6">
              <h3 class="font-semibold text-gray-900 pb-1  hover:text-black">
                <a href="https://hasob.com.ng/">Hasob</a>
              </h3>
              <p class="text-md text-gray-600 font-light">
                Software Engineer | Facilitator{" "}
                <span className="pl-12 text-sm italic">
                  Nov 2021 - March 2022
                </span>
              </p>
              <hr className="mt-4" />
            </div>

            {/* Fiverr */}
            <div class="mb-6">
              <h3 class="font-semibold text-gray-900 pb-1  hover:text-black">
                <a href="https://www.fiverr.com/">Fiverr | Upwork</a>
              </h3>
              <p class="text-md text-gray-600 font-light">
                Freelancer | Software Engineer{" "}
                <span className="pl-12 text-sm italic">
                  Jun 2019 - March 2022
                </span>
              </p>
              <hr className="mt-4" />
            </div>

            {/* Tech4dev */}
            <div class="mb-6">
              <h3 class="font-semibold text-gray-900 pb-1  hover:text-black">
                <a href="https://tech4dev.com/">Tech4Dev</a>
              </h3>
              <p class="text-md text-gray-600 font-light">
                Software Engineer{" "}
                <span className="pl-12 text-sm italic">
                  May 2021 - Oct 2021
                </span>
              </p>
              <hr className="mt-4" />
            </div>

            {/* Tech4dev */}
            <div class="mb-6">
              <h3 class="font-semibold text-gray-900 pb-1  hover:text-black">
                <a href="https://gdli.edu.ng/">
                  Global DIstance Learning Institute
                </a>
              </h3>
              <p class="text-md text-gray-600 font-light">
                Software Engineer Intern{" "}
                <span className="pl-12 text-sm italic">
                  Feb 2018 - Jan 2021
                </span>
              </p>
            </div>
          </div>
        </div>

        {/* Projects */}
        <div class="block pt-9 md:flex">
          <div class="pb-6  w-2/12 md:p-0">
            <h2 class="font-xs font-light tracking-widest text-sm text-gray-600 leading-normal uppercase text-right pr-20">
              Projects
            </h2>
          </div>
          <div class=" text-lg text-gray-600 font-light  w-8/12 ">
            <div class="mb-6">
              <h3 class="font-semibold text-gray-900 pb-1 hover:underline hover:text-black">
                <a href="https://www.nexthandle.com/">Nexthandle</a>
              </h3>
              <p class="text-md text-gray-600 font-light">
                This a tour Application where one can easily go Checkout the
                Places he or she has visited or ben
              </p>
            </div>
            <div class="mb-6">
              <h3 class="font-semibold text-gray-900 pb-1 hover:underline hover:text-black">
                <a href="#">Tour Application</a>
              </h3>
              <p class="text-md text-gray-600 font-light">
                This a tour Application where one can easily go Checkout the
                Places he or she has visited or ben
              </p>
            </div>
            <div class="mb-6">
              <h3 class="font-semibold text-gray-900 pb-1 hover:underline hover:text-black">
                <a href="https://mini-ecomerce-platform.vercel.app/">
                  Mini e-commerce Appliction
                </a>
              </h3>
              <p class="text-md text-gray-600 font-light">
                This is mini e-commerce Application, come and others as well.
              </p>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </Layout>
  );
}
